//
// GRIP Generated file: 2016-11-16T22:14:06Z
// GRIP: this module is auto-generated using Java Freemarker tool
// GRIP: Auto-generated via template engine and edit only for customization


// this is autogenerated by reading in the register information from the IPXact description of the system

#ifndef __GRAYFILTER_REGMAP_H__
#define __GRAYFILTER_REGMAP_H__

#include "../platform/common.h"



typedef struct {
	RegType AP_CTRL;
	RegType GIE;
	RegType IER;
	RegType ISR;
	RegType ROWS_DATA;
	RegType COLS_DATA;
} grayfilterIP_RegMap;



#endif
