// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xce.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCe_CfgInitialize(XCe *InstancePtr, XCe_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Slv_para_BaseAddress = ConfigPtr->Slv_para_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCe_Start(XCe *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_AP_CTRL) & 0x80;
    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCe_IsDone(XCe *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCe_IsIdle(XCe *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCe_IsReady(XCe *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCe_EnableAutoRestart(XCe *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_AP_CTRL, 0x80);
}

void XCe_DisableAutoRestart(XCe *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_AP_CTRL, 0);
}

void XCe_SetWidth(XCe *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_WIDTH_DATA, Data);
}

u32 XCe_GetWidth(XCe *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_WIDTH_DATA);
    return Data;
}

void XCe_SetHeight(XCe *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_HEIGHT_DATA, Data);
}

u32 XCe_GetHeight(XCe *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_HEIGHT_DATA);
    return Data;
}

void XCe_SetCsd1(XCe *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_CSD1_DATA, Data);
}

u32 XCe_GetCsd1(XCe *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_CSD1_DATA);
    return Data;
}

void XCe_SetCsd2(XCe *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_CSD2_DATA, Data);
}

u32 XCe_GetCsd2(XCe *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_CSD2_DATA);
    return Data;
}

void XCe_SetEpsilon(XCe *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_EPSILON_DATA, Data);
}

u32 XCe_GetEpsilon(XCe *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_EPSILON_DATA);
    return Data;
}

void XCe_SetReadaddress(XCe *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_READADDRESS_DATA, Data);
}

u32 XCe_GetReadaddress(XCe *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_READADDRESS_DATA);
    return Data;
}

void XCe_SetWriteaddress(XCe *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_WRITEADDRESS_DATA, Data);
}

u32 XCe_GetWriteaddress(XCe *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_WRITEADDRESS_DATA);
    return Data;
}

void XCe_InterruptGlobalEnable(XCe *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_GIE, 1);
}

void XCe_InterruptGlobalDisable(XCe *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_GIE, 0);
}

void XCe_InterruptEnable(XCe *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_IER);
    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_IER, Register | Mask);
}

void XCe_InterruptDisable(XCe *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_IER);
    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_IER, Register & (~Mask));
}

void XCe_InterruptClear(XCe *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCe_WriteReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_ISR, Mask);
}

u32 XCe_InterruptGetEnabled(XCe *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_IER);
}

u32 XCe_InterruptGetStatus(XCe *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCe_ReadReg(InstancePtr->Slv_para_BaseAddress, XCE_SLV_PARA_ADDR_ISR);
}

