// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xce.h"

extern XCe_Config XCe_ConfigTable[];

XCe_Config *XCe_LookupConfig(u16 DeviceId) {
	XCe_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCE_NUM_INSTANCES; Index++) {
		if (XCe_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XCe_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XCe_Initialize(XCe *InstancePtr, u16 DeviceId) {
	XCe_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XCe_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XCe_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

