// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmatchingengine32.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMatchingengine32_CfgInitialize(XMatchingengine32 *InstancePtr, XMatchingengine32_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Slv_para_BaseAddress = ConfigPtr->Slv_para_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMatchingengine32_Start(XMatchingengine32 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_AP_CTRL) & 0x80;
    XMatchingengine32_WriteReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMatchingengine32_IsDone(XMatchingengine32 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMatchingengine32_IsIdle(XMatchingengine32 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMatchingengine32_IsReady(XMatchingengine32 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMatchingengine32_EnableAutoRestart(XMatchingengine32 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatchingengine32_WriteReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_AP_CTRL, 0x80);
}

void XMatchingengine32_DisableAutoRestart(XMatchingengine32 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatchingengine32_WriteReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_AP_CTRL, 0);
}

u32 XMatchingengine32_GetReturn(XMatchingengine32 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_AP_RETURN);
    return Data;
}
void XMatchingengine32_SetHeight_v(XMatchingengine32 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatchingengine32_WriteReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_HEIGHT_V_DATA, Data);
}

u32 XMatchingengine32_GetHeight_v(XMatchingengine32 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_HEIGHT_V_DATA);
    return Data;
}

void XMatchingengine32_SetWidth_v(XMatchingengine32 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatchingengine32_WriteReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_WIDTH_V_DATA, Data);
}

u32 XMatchingengine32_GetWidth_v(XMatchingengine32 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_WIDTH_V_DATA);
    return Data;
}

void XMatchingengine32_SetReadaddress1_v(XMatchingengine32 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatchingengine32_WriteReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_READADDRESS1_V_DATA, Data);
}

u32 XMatchingengine32_GetReadaddress1_v(XMatchingengine32 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_READADDRESS1_V_DATA);
    return Data;
}

void XMatchingengine32_SetReadaddress2_v(XMatchingengine32 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatchingengine32_WriteReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_READADDRESS2_V_DATA, Data);
}

u32 XMatchingengine32_GetReadaddress2_v(XMatchingengine32 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_READADDRESS2_V_DATA);
    return Data;
}

void XMatchingengine32_SetFeatureout_v(XMatchingengine32 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatchingengine32_WriteReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_FEATUREOUT_V_DATA, Data);
}

u32 XMatchingengine32_GetFeatureout_v(XMatchingengine32 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_FEATUREOUT_V_DATA);
    return Data;
}

void XMatchingengine32_InterruptGlobalEnable(XMatchingengine32 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatchingengine32_WriteReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_GIE, 1);
}

void XMatchingengine32_InterruptGlobalDisable(XMatchingengine32 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatchingengine32_WriteReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_GIE, 0);
}

void XMatchingengine32_InterruptEnable(XMatchingengine32 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_IER);
    XMatchingengine32_WriteReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_IER, Register | Mask);
}

void XMatchingengine32_InterruptDisable(XMatchingengine32 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_IER);
    XMatchingengine32_WriteReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_IER, Register & (~Mask));
}

void XMatchingengine32_InterruptClear(XMatchingengine32 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMatchingengine32_WriteReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_ISR, Mask);
}

u32 XMatchingengine32_InterruptGetEnabled(XMatchingengine32 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_IER);
}

u32 XMatchingengine32_InterruptGetStatus(XMatchingengine32 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMatchingengine32_ReadReg(InstancePtr->Slv_para_BaseAddress, XMATCHINGENGINE32_SLV_PARA_ADDR_ISR);
}

