// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmatchingengine32.h"

extern XMatchingengine32_Config XMatchingengine32_ConfigTable[];

XMatchingengine32_Config *XMatchingengine32_LookupConfig(u16 DeviceId) {
	XMatchingengine32_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMATCHINGENGINE32_NUM_INSTANCES; Index++) {
		if (XMatchingengine32_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMatchingengine32_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMatchingengine32_Initialize(XMatchingengine32 *InstancePtr, u16 DeviceId) {
	XMatchingengine32_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMatchingengine32_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMatchingengine32_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

