
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmatchingengine32.h"

/*
* The configuration table for devices
*/

XMatchingengine32_Config XMatchingengine32_ConfigTable[] =
{
	{
		XPAR_MATCHINGENGINE32_TOP_0_DEVICE_ID,
		XPAR_MATCHINGENGINE32_TOP_0_S_AXI_SLV_PARA_BASEADDR
	}
};


