
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xeee.h"

/*
* The configuration table for devices
*/

XEee_Config XEee_ConfigTable[] =
{
	{
		XPAR_EEE_TOP_0_DEVICE_ID,
		XPAR_EEE_TOP_0_S_AXI_AXI_LITE_PARA_BASEADDR
	}
};


