// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xeee.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEee_CfgInitialize(XEee *InstancePtr, XEee_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axi_lite_para_BaseAddress = ConfigPtr->Axi_lite_para_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEee_Start(XEee *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_AP_CTRL) & 0x80;
    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_AP_CTRL, Data | 0x01);
}

u32 XEee_IsDone(XEee *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XEee_IsIdle(XEee *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XEee_IsReady(XEee *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XEee_EnableAutoRestart(XEee *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_AP_CTRL, 0x80);
}

void XEee_DisableAutoRestart(XEee *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_AP_CTRL, 0);
}

void XEee_SetMatchcount_v(XEee *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_MATCHCOUNT_V_DATA, Data);
}

u32 XEee_GetMatchcount_v(XEee *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_MATCHCOUNT_V_DATA);
    return Data;
}

void XEee_SetFaddr_v(XEee *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_FADDR_V_DATA, Data);
}

u32 XEee_GetFaddr_v(XEee *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_FADDR_V_DATA);
    return Data;
}

void XEee_SetVecoutaddr_v(XEee *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_VECOUTADDR_V_DATA, Data);
}

u32 XEee_GetVecoutaddr_v(XEee *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_VECOUTADDR_V_DATA);
    return Data;
}

void XEee_SetModeladdr_v(XEee *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_MODELADDR_V_DATA, Data);
}

u32 XEee_GetModeladdr_v(XEee *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_MODELADDR_V_DATA);
    return Data;
}

void XEee_SetModelcount_v(XEee *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_MODELCOUNT_V_DATA, Data);
}

u32 XEee_GetModelcount_v(XEee *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_MODELCOUNT_V_DATA);
    return Data;
}

void XEee_SetErrthres_v(XEee *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_ERRTHRES_V_DATA, Data);
}

u32 XEee_GetErrthres_v(XEee *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_ERRTHRES_V_DATA);
    return Data;
}

void XEee_SetResultaddr_v(XEee *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_RESULTADDR_V_DATA, Data);
}

u32 XEee_GetResultaddr_v(XEee *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_RESULTADDR_V_DATA);
    return Data;
}

void XEee_SetMode_v(XEee *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_MODE_V_DATA, Data);
}

u32 XEee_GetMode_v(XEee *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_MODE_V_DATA);
    return Data;
}

void XEee_InterruptGlobalEnable(XEee *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_GIE, 1);
}

void XEee_InterruptGlobalDisable(XEee *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_GIE, 0);
}

void XEee_InterruptEnable(XEee *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_IER);
    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_IER, Register | Mask);
}

void XEee_InterruptDisable(XEee *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_IER);
    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_IER, Register & (~Mask));
}

void XEee_InterruptClear(XEee *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEee_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_ISR, Mask);
}

u32 XEee_InterruptGetEnabled(XEee *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_IER);
}

u32 XEee_InterruptGetStatus(XEee *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEee_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XEEE_AXI_LITE_PARA_ADDR_ISR);
}

