// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xeee.h"

extern XEee_Config XEee_ConfigTable[];

XEee_Config *XEee_LookupConfig(u16 DeviceId) {
	XEee_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XEEE_NUM_INSTANCES; Index++) {
		if (XEee_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XEee_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XEee_Initialize(XEee *InstancePtr, u16 DeviceId) {
	XEee_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XEee_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XEee_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

