// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// slv_para
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : reserved
// 0x14 : Data signal of width
//        bit 10~0 - width[10:0] (Read/Write)
//        others   - reserved
// 0x18 : reserved
// 0x1c : Data signal of height
//        bit 10~0 - height[10:0] (Read/Write)
//        others   - reserved
// 0x20 : reserved
// 0x24 : Data signal of csd1
//        bit 7~0 - csd1[7:0] (Read/Write)
//        others  - reserved
// 0x28 : reserved
// 0x2c : Data signal of csd2
//        bit 7~0 - csd2[7:0] (Read/Write)
//        others  - reserved
// 0x30 : reserved
// 0x34 : Data signal of epsilon
//        bit 7~0 - epsilon[7:0] (Read/Write)
//        others  - reserved
// 0x38 : reserved
// 0x3c : Data signal of readaddress
//        bit 31~0 - readaddress[31:0] (Read/Write)
// 0x40 : reserved
// 0x44 : Data signal of writeaddress
//        bit 31~0 - writeaddress[31:0] (Read/Write)
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XCE_SLV_PARA_ADDR_AP_CTRL           0x00
#define XCE_SLV_PARA_ADDR_GIE               0x04
#define XCE_SLV_PARA_ADDR_IER               0x08
#define XCE_SLV_PARA_ADDR_ISR               0x0c
#define XCE_SLV_PARA_ADDR_WIDTH_DATA        0x14
#define XCE_SLV_PARA_BITS_WIDTH_DATA        11
#define XCE_SLV_PARA_ADDR_HEIGHT_DATA       0x1c
#define XCE_SLV_PARA_BITS_HEIGHT_DATA       11
#define XCE_SLV_PARA_ADDR_CSD1_DATA         0x24
#define XCE_SLV_PARA_BITS_CSD1_DATA         8
#define XCE_SLV_PARA_ADDR_CSD2_DATA         0x2c
#define XCE_SLV_PARA_BITS_CSD2_DATA         8
#define XCE_SLV_PARA_ADDR_EPSILON_DATA      0x34
#define XCE_SLV_PARA_BITS_EPSILON_DATA      8
#define XCE_SLV_PARA_ADDR_READADDRESS_DATA  0x3c
#define XCE_SLV_PARA_BITS_READADDRESS_DATA  32
#define XCE_SLV_PARA_ADDR_WRITEADDRESS_DATA 0x44
#define XCE_SLV_PARA_BITS_WRITEADDRESS_DATA 32

