// NOTE: this would later be generated by the template engine using information from "SoC_config.h", "sw_functions.h"
// NOTE: right now simulating the scenario when there is a dual core ARM Cortex A9 on Zynq-PS and a Xilinx Microblaze core on Zynq-PL are available then the template engine would generate the following file

#ifndef SOCPROC_SUPPORT_H_
#define SOCPROC_SUPPORT_H_

#include "ZYNQ_ARM_CORTEX_A9_support.h"
#include "XIL_MICROBLAZE_8_5_support.h"
// NOTE: and so on for other processors...the system architect knows the processors available for the targeted platform so including support files for each one of them...it is possible though that not all of them are used in the final GRIP architecture


//#include "SoCProc_support_config.h"


// API for application developer
void SoCProc_initialize();
unsigned char SoCProc_processDataflow();


#endif


// all the code in this module shall be executed by Master CPU only!!
