

// NOTE: this would later be generated by the template engine

#include "SoCProc_support.h"
#include <stdlib.h>



void SoCProc_initialize() {
    ZYNQ_ARM_CORTEX_A9_initialize();            // this would initialize all the processor instances of this type and associate each one with a unique SoCProc element (from _config)
    XIL_MICROBLAZE_8_5_initialize();            // this would initialize all the processor instances of this type and associate each one with a unique SoCProc element (from _config)
    // and so on if other processors are available in the design...this info is known to code generator targeting a specific platform   		
}


unsigned char SoCProc_processDataflow() {
	if (ZYNQ_ARM_CORTEX_A9_process() == 1) {	     // this processor type has the highest priority!!
	    return 1;                                   // a free processor is available for this type
	} else if (XIL_MICROBLAZE_8_5_process() == 1) {
	    return 1;                                   // a free processor is available for this type
	}
	
	return 0;               // no processor of any type is available
}








