// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XECE_H
#define XECE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xece_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axi_lite_para_BaseAddress;
} XEce_Config;
#endif

typedef struct {
    u32 Axi_lite_para_BaseAddress;
    u32 IsReady;
} XEce;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XEce_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XEce_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XEce_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XEce_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XEce_Initialize(XEce *InstancePtr, u16 DeviceId);
XEce_Config* XEce_LookupConfig(u16 DeviceId);
int XEce_CfgInitialize(XEce *InstancePtr, XEce_Config *ConfigPtr);
#else
int XEce_Initialize(XEce *InstancePtr, const char* InstanceName);
int XEce_Release(XEce *InstancePtr);
#endif

void XEce_Start(XEce *InstancePtr);
u32 XEce_IsDone(XEce *InstancePtr);
u32 XEce_IsIdle(XEce *InstancePtr);
u32 XEce_IsReady(XEce *InstancePtr);
void XEce_EnableAutoRestart(XEce *InstancePtr);
void XEce_DisableAutoRestart(XEce *InstancePtr);
u32 XEce_GetReturn(XEce *InstancePtr);

void XEce_SetBestmodeladdr_v(XEce *InstancePtr, u32 Data);
u32 XEce_GetBestmodeladdr_v(XEce *InstancePtr);
void XEce_SetFullvectoraddr_v(XEce *InstancePtr, u32 Data);
u32 XEce_GetFullvectoraddr_v(XEce *InstancePtr);
void XEce_SetVeccount_v(XEce *InstancePtr, u32 Data);
u32 XEce_GetVeccount_v(XEce *InstancePtr);
void XEce_SetResultvectoraddr_v(XEce *InstancePtr, u32 Data);
u32 XEce_GetResultvectoraddr_v(XEce *InstancePtr);
void XEce_SetErrthres_v(XEce *InstancePtr, u32 Data);
u32 XEce_GetErrthres_v(XEce *InstancePtr);

void XEce_InterruptGlobalEnable(XEce *InstancePtr);
void XEce_InterruptGlobalDisable(XEce *InstancePtr);
void XEce_InterruptEnable(XEce *InstancePtr, u32 Mask);
void XEce_InterruptDisable(XEce *InstancePtr, u32 Mask);
void XEce_InterruptClear(XEce *InstancePtr, u32 Mask);
u32 XEce_InterruptGetEnabled(XEce *InstancePtr);
u32 XEce_InterruptGetStatus(XEce *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
