// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xece.h"

extern XEce_Config XEce_ConfigTable[];

XEce_Config *XEce_LookupConfig(u16 DeviceId) {
	XEce_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XECE_NUM_INSTANCES; Index++) {
		if (XEce_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XEce_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XEce_Initialize(XEce *InstancePtr, u16 DeviceId) {
	XEce_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XEce_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XEce_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

