// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xece.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEce_CfgInitialize(XEce *InstancePtr, XEce_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axi_lite_para_BaseAddress = ConfigPtr->Axi_lite_para_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEce_Start(XEce *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_AP_CTRL) & 0x80;
    XEce_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_AP_CTRL, Data | 0x01);
}

u32 XEce_IsDone(XEce *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XEce_IsIdle(XEce *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XEce_IsReady(XEce *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XEce_EnableAutoRestart(XEce *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEce_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_AP_CTRL, 0x80);
}

void XEce_DisableAutoRestart(XEce *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEce_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_AP_CTRL, 0);
}

u32 XEce_GetReturn(XEce *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_AP_RETURN);
    return Data;
}
void XEce_SetBestmodeladdr_v(XEce *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEce_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_BESTMODELADDR_V_DATA, Data);
}

u32 XEce_GetBestmodeladdr_v(XEce *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_BESTMODELADDR_V_DATA);
    return Data;
}

void XEce_SetFullvectoraddr_v(XEce *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEce_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_FULLVECTORADDR_V_DATA, Data);
}

u32 XEce_GetFullvectoraddr_v(XEce *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_FULLVECTORADDR_V_DATA);
    return Data;
}

void XEce_SetVeccount_v(XEce *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEce_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_VECCOUNT_V_DATA, Data);
}

u32 XEce_GetVeccount_v(XEce *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_VECCOUNT_V_DATA);
    return Data;
}

void XEce_SetResultvectoraddr_v(XEce *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEce_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_RESULTVECTORADDR_V_DATA, Data);
}

u32 XEce_GetResultvectoraddr_v(XEce *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_RESULTVECTORADDR_V_DATA);
    return Data;
}

void XEce_SetErrthres_v(XEce *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEce_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_ERRTHRES_V_DATA, Data);
}

u32 XEce_GetErrthres_v(XEce *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_ERRTHRES_V_DATA);
    return Data;
}

void XEce_InterruptGlobalEnable(XEce *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEce_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_GIE, 1);
}

void XEce_InterruptGlobalDisable(XEce *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEce_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_GIE, 0);
}

void XEce_InterruptEnable(XEce *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_IER);
    XEce_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_IER, Register | Mask);
}

void XEce_InterruptDisable(XEce *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_IER);
    XEce_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_IER, Register & (~Mask));
}

void XEce_InterruptClear(XEce *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEce_WriteReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_ISR, Mask);
}

u32 XEce_InterruptGetEnabled(XEce *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_IER);
}

u32 XEce_InterruptGetStatus(XEce *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEce_ReadReg(InstancePtr->Axi_lite_para_BaseAddress, XECE_AXI_LITE_PARA_ADDR_ISR);
}

