// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// axi_lite_para
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : reserved
// 0x14 : Data signal of bestModelAddr_V
//        bit 31~0 - bestModelAddr_V[31:0] (Read/Write)
// 0x18 : reserved
// 0x1c : Data signal of fullVectorAddr_V
//        bit 31~0 - fullVectorAddr_V[31:0] (Read/Write)
// 0x20 : reserved
// 0x24 : Data signal of veccount_V
//        bit 15~0 - veccount_V[15:0] (Read/Write)
//        others   - reserved
// 0x28 : reserved
// 0x2c : Data signal of resultVectorAddr_V
//        bit 31~0 - resultVectorAddr_V[31:0] (Read/Write)
// 0x30 : reserved
// 0x34 : Data signal of errthres_V
//        bit 3~0 - errthres_V[3:0] (Read/Write)
//        others  - reserved
// 0x38 : Data signal of ap_return
//        bit 15~0 - ap_return[15:0] (Read)
//        others   - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XECE_AXI_LITE_PARA_ADDR_AP_CTRL                 0x00
#define XECE_AXI_LITE_PARA_ADDR_GIE                     0x04
#define XECE_AXI_LITE_PARA_ADDR_IER                     0x08
#define XECE_AXI_LITE_PARA_ADDR_ISR                     0x0c
#define XECE_AXI_LITE_PARA_ADDR_BESTMODELADDR_V_DATA    0x14
#define XECE_AXI_LITE_PARA_BITS_BESTMODELADDR_V_DATA    32
#define XECE_AXI_LITE_PARA_ADDR_FULLVECTORADDR_V_DATA   0x1c
#define XECE_AXI_LITE_PARA_BITS_FULLVECTORADDR_V_DATA   32
#define XECE_AXI_LITE_PARA_ADDR_VECCOUNT_V_DATA         0x24
#define XECE_AXI_LITE_PARA_BITS_VECCOUNT_V_DATA         16
#define XECE_AXI_LITE_PARA_ADDR_RESULTVECTORADDR_V_DATA 0x2c
#define XECE_AXI_LITE_PARA_BITS_RESULTVECTORADDR_V_DATA 32
#define XECE_AXI_LITE_PARA_ADDR_ERRTHRES_V_DATA         0x34
#define XECE_AXI_LITE_PARA_BITS_ERRTHRES_V_DATA         4
#define XECE_AXI_LITE_PARA_ADDR_AP_RETURN               0x38
#define XECE_AXI_LITE_PARA_BITS_AP_RETURN               16

