// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// slv_para
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : reserved
// 0x14 : Data signal of height_V
//        bit 9~0 - height_V[9:0] (Read/Write)
//        others  - reserved
// 0x18 : reserved
// 0x1c : Data signal of width_V
//        bit 9~0 - width_V[9:0] (Read/Write)
//        others  - reserved
// 0x20 : reserved
// 0x24 : Data signal of readaddress1_V
//        bit 31~0 - readaddress1_V[31:0] (Read/Write)
// 0x28 : reserved
// 0x2c : Data signal of readaddress2_V
//        bit 31~0 - readaddress2_V[31:0] (Read/Write)
// 0x30 : reserved
// 0x34 : Data signal of featureout_V
//        bit 31~0 - featureout_V[31:0] (Read/Write)
// 0x38 : Data signal of ap_return
//        bit 15~0 - ap_return[15:0] (Read)
//        others   - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XMATCHINGENGINE32_SLV_PARA_ADDR_AP_CTRL             0x00
#define XMATCHINGENGINE32_SLV_PARA_ADDR_GIE                 0x04
#define XMATCHINGENGINE32_SLV_PARA_ADDR_IER                 0x08
#define XMATCHINGENGINE32_SLV_PARA_ADDR_ISR                 0x0c
#define XMATCHINGENGINE32_SLV_PARA_ADDR_HEIGHT_V_DATA       0x14
#define XMATCHINGENGINE32_SLV_PARA_BITS_HEIGHT_V_DATA       10
#define XMATCHINGENGINE32_SLV_PARA_ADDR_WIDTH_V_DATA        0x1c
#define XMATCHINGENGINE32_SLV_PARA_BITS_WIDTH_V_DATA        10
#define XMATCHINGENGINE32_SLV_PARA_ADDR_READADDRESS1_V_DATA 0x24
#define XMATCHINGENGINE32_SLV_PARA_BITS_READADDRESS1_V_DATA 32
#define XMATCHINGENGINE32_SLV_PARA_ADDR_READADDRESS2_V_DATA 0x2c
#define XMATCHINGENGINE32_SLV_PARA_BITS_READADDRESS2_V_DATA 32
#define XMATCHINGENGINE32_SLV_PARA_ADDR_FEATUREOUT_V_DATA   0x34
#define XMATCHINGENGINE32_SLV_PARA_BITS_FEATUREOUT_V_DATA   32
#define XMATCHINGENGINE32_SLV_PARA_ADDR_AP_RETURN           0x38
#define XMATCHINGENGINE32_SLV_PARA_BITS_AP_RETURN           16

