// this module is auto-generated by GRIP framework using the functions provided by IP suppliers to provide an API to application developer


#ifndef __FUNCS_H__
#define __FUNCS_H__

#include "./GrayscaleIP/SW/function/GrayscaleIP_func.h"
#include "./SobelIP/SW/function/SobelIP_func.h"
#include "./ErodeIP/SW/function/ErodeIP_func.h"
#include "xscugic.h"

// API
extern void GrayscaleIP_func_init(XScuGic *InterruptController, unsigned long ImgIn_BaseAddr,unsigned long ImgOut_BaseAddr,unsigned short width, unsigned short height, unsigned short horizontalActiveTime, unsigned short verticalActiveTime);
extern void ConvToGray_func(unsigned long ImgIn_BaseAddr,unsigned long ImgOut_BaseAddr,unsigned short width, unsigned short height, unsigned short horizontalActiveTime, unsigned short verticalActiveTime);

extern void EdgeDetection_func(unsigned long ImgIn_BaseAddr,unsigned long ImgOut_BaseAddr, unsigned short width, unsigned short height, unsigned short horizontalActiveTime, unsigned short vertcialActiveTime);

extern void Erode_func(unsigned long ImgIn_BaseAddr, unsigned long ImgOut_BaseAddr, unsigned short width, unsigned short height, unsigned short horizontalActiveTime, unsigned short verticalActiveTime);



#endif
